import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import useIndex from '../data/hooks/pages/useIndex.page'
import PostList from '../ui/components/PostList/PostList';
import styles from '../ui/styles/Home.module.css'

const Home: NextPage = () => {
  const { posts } = useIndex();

  return (
    <div className={styles.container}>
      <Head>
        <title>TreinaBlog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <PostList posts={posts} />
      </main>
    </div>
  )
}

export default Home
